[build-system]
requires = ["hatchling>=1.26", "hatch-vcs>=0.5"]
build-backend = "hatchling.build"

[project]
name = "warp-journal"
dynamic = ["version"]
description = "Honkai: Star Rail gacha tracker and analysis."
authors = [{name = "Ennea"}, {name = "FichteFoll", email = "fichtefoll2@googlemail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bottle>=0.12.25,<0.14",
    "gevent>22.10",
    "gevent-websocket>=0.10.1,<0.11",
    "greenlet>=3.0.0,<4",
    "zope.event>=4.6,<5",
    "zope.interface>=6.0,<7",
]

[project.scripts]
warp-journal = "warp_journal.__main__:main"

[project.optional-dependencies]
dev = [
    "flake8>=6.0.0,<7",
]

[dependency-groups]
windows-build = [
    "nuitka; sys_platform == 'win32'",
    "ordered-set; sys_platform == 'win32'",
    "zstandard; sys_platform == 'win32'",
]

[tool.hatch.build.targets.wheel]
packages = ["warp_journal"]

[tool.hatch.version]
source = "vcs"
fallback-version = "1.1.0"

[tool.hatch.version.raw-options]
version_scheme = "no-guess-dev"

[tool.hatch.build.hooks.vcs]
version-file = "warp_journal/_version.py"

[tool.pyright]
defineConstant = { DEBUG = true }

reportMissingTypeStubs = "information"
reportImportCycles = "warning"

pythonVersion = "3.10"
pythonPlatform = "All"
